words:
  class: sfPropelRouteCollection
  options:
    model:                Words
    module:               words
    prefix_path:          words
    column:               id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: words, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
