<?php


/**
 * This class adds structure of 'games' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 10/11/09 12:20:16
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class GamesMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.GamesMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(GamesPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(GamesPeer::TABLE_NAME);
		$tMap->setPhpName('Games');
		$tMap->setClassname('Games');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('PLAYER1_ID', 'Player1Id', 'INTEGER', 'player', 'ID', true, null);

		$tMap->addForeignKey('PLAYER2_ID', 'Player2Id', 'INTEGER', 'player', 'ID', false, null);

		$tMap->addForeignKey('WORD_ID', 'WordId', 'INTEGER', 'words', 'ID', true, null);

		$tMap->addColumn('PLAYER_TURN', 'PlayerTurn', 'INTEGER', true, null);

		$tMap->addColumn('PLAYER1_FAULTS', 'Player1Faults', 'INTEGER', false, null);

		$tMap->addColumn('PLAYER2_FAULTS', 'Player2Faults', 'INTEGER', false, null);

		$tMap->addColumn('USED_LETTERS', 'UsedLetters', 'VARCHAR', false, 500);

		$tMap->addColumn('NEW_GAME_PLAYER1', 'NewGamePlayer1', 'BOOLEAN', false, null);

		$tMap->addColumn('NEW_GAME_PLAYER2', 'NewGamePlayer2', 'BOOLEAN', false, null);

		$tMap->addColumn('NEW_GAME_STARTED', 'NewGameStarted', 'BOOLEAN', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // GamesMapBuilder
